---
- name: Deploy Docker Containers
  hosts: localhost
  become: true
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker
    
    - name: Pull sapi Docker image
      docker_image:
        name: "echol0t/sapi-image"
        tag: "{{ docker_image_version }}"
        source: pull
    
    - name: Create Docker network
      docker_network:
        name: my_network

    - name: Run sapi web container with environment variables
      docker_container:
        name: "web"
        image: "echol0t/sapi-image:{{ docker_image_version }}"
        state: started
        restart_policy: always
        ports:
          - "80:80"
        networks:
          - name: my_network
